### PR TITLE
Retrieve solution before closing the gurobi env

### PR DESCRIPTION
**Pull request by dannyopts**
Currently the Gurobi env is closed before the solution has been retrieved and this can result in an exception being thrown based on a race condition (described in the issue referenced below)

Fixes https://github.com/PyPSA/linopy/issues/192

### CODE REVIEW

**Comment by dannyopts** [comment]
Does the fact coverage has gone down mean we cant merge this PR?

It seems to me this is not a change that would require a test, but if it would normally be accompanied by a test, can someone give me a steer what that would look like?

**Comment by FabianHofmann** [comment]
Thanks @dannyopts, the diffs are a bit hard to read. But it seems you intended the block which was not in the with block, is that right? I would not worry about the code coverage of the patch.

**Comment by dannyopts** [comment]
@FabianHofmann yes exactly, we dont exit the stack until after we have read the solution so the gurobi env is not destroyed.

**Comment by FabianHofmann** [comment]
great, thanks!

**Pull request merged**
