### PR TITLE
fix: no sol file for gurobi

### PR DESCRIPTION
**Pull request by michalmarszal**

### CODE REVIEW

**Comment by FabianHofmann** [comment]
@michalmarszal you mind if I push an additional commit to fix for the other solvers?

**Review by FabianHofmann — APPROVED** [review]

**Comment by FabianHofmann** [comment]
@michalmarszal I took the freedom, thanks for the contribution!

**Comment by michalmarszal** [comment]
> @michalmarszal you mind if I push an additional commit to fix for the other solvers?

No problem. Feel free to modify for the other solvers. I don't have access to all of them.

**Comment by FabianHofmann** [comment]
FYI: it is going a bit back and forth as I also don't have them all locally

**Pull request merged**
