### PR TITLE
Fix HiGHS interface for Windows

### PR DESCRIPTION
**Pull request by avautrin**
HiGHS interface was not functional in v0.0.13, the fix solves the issue

### CODE REVIEW

**Comment by avautrin** [comment]
Actually not sure whether it can be fixed as it is not the most recent version... But v0.0.14 and higher require highspy which is not available on Windows

**Comment by FabianHofmann** [comment]
Hey @avautrin, it seems that you are on a old version of linopy, which still relies on the terminal execution of highs. With newer versions, linopy uses highspy for the interface. However I am not sure what the status for highspy on Windows machines is...

**Comment by avautrin** [comment]
Hi @FabianHofmann, indeed, I had to stick to the 0.0.13 version which did not require highspy, as it is not functional yet... But 0.0.13 was not working because of a few typos in the code, hence the PR I propose. The fix is needed for HiGHS to work on Windows but I understand it may not be possible given the change in interface used

**Comment by FabianHofmann** [comment]
Yes, I am sorry for this. Unfortunately it seems that highspy is not yet available for Windows machines... I am also waiting for this, because then we can set it to the default solver.

**Comment by fneum** [comment]
https://pypi.org/project/highspy/1.5.0.dev0/#files

1.5 seems to include wheels for Windows?

**Comment by FabianHofmann** [comment]
> https://pypi.org/project/highspy/1.5.0.dev0/#files
> 
> 1.5 seems to include wheels for Windows?

Uh interesting, I did not see it and was waiting for https://github.com/ERGO-Code/HiGHS/issues/925 to be closed. But let's try out.

**Comment by FabianHofmann** [comment]
@avautrin could you do us a favor and check out this PR https://github.com/PyPSA/linopy/pull/89 and see whether things are working on a win machine? 

* clone the repo
* git checkout highspy-default-solver
* pip install -e .[dev]
* pytest 

It seem that the CI still has some problems here, but I cannot figure out which.

**Comment by avautrin** [comment]
[linopy-higshpy-default-solver.txt](https://github.com/PyPSA/linopy/files/10445305/linopy-higshpy-default-solver.txt)
[highspy.txt](https://github.com/PyPSA/linopy/files/10445313/highspy.txt)

Hello @FabianHofmann, I tried to run the commands but end with the logs in linopy-highspy-default-solver.txt.
On highspy, it is possible that it works on Windows but running minimal.py from the HiGHS repo (https://github.com/ERGO-Code/HiGHS/blob/master/examples/minimal.py) yields errors too (the one in highspy.txt)

**Comment by avautrin** [comment]
Installing highspy works, but importing it in a shell yields the DLL load error copied in highspy.txt (above). It is like some libraries are missing/not compatible, yet I directly started from a fresh venv

**Comment by avautrin** [comment]
It was a matter of Python version in one of the environments... highspy works for me, we can close the discussion. Thanks a lot for your help!

**Comment by avautrin** [comment]
Acutally one last issue @FabianHofmann: when running linopy with highspy, linopy does not extract the dual variable and shows the primal value only. Was there a change from the command line HiGHS executable, or an option I missed?

**Comment by FabianHofmann** [comment]
@avautrin 
About the dual problem: is that with the very last version of linopy? 
Could share your wisdom on the highspy installation and python version? I am not able to install highspy on the Github machines properly...

**Comment by avautrin** [comment]
I am currently using linopy 0.0.15, as PyPSA requires versions below 0.1 (if I'm not wrong?)
For highspy, what helped me a lot (worked with conda) was to have a clean base environment, move python to 3.10.9 in the project env, and load all libraries with conda (except highspy and pypsa which were only available on pip)

**Comment by avautrin** [comment]
Hi @FabianHofmann, did you have a chance to look at this issue on duals? Or maybe it is on the PyPSA side that something is wrong?

**Comment by FabianHofmann** [comment]
@avautrin that's correct. This works for me:

```
import pypsa
n = pypsa.examples.ac_dc_meshed()
n.optimize(solver_name='highs')
n.buses_t.marginal_price
```
Does it for you?

**Comment by avautrin** [comment]
It does not, and prints the primal values instead (same as n.loads_t.p_set)... I have PyPSA 0.21.3, linopy 0.0.15 and highspy 1.5.0.dev0, what versions do you use on your side?

```
INFO:linopy.model: Solve linear problem using Highs solver
INFO:linopy.io: Writing time: 0.22s
Running HiGHS 1.5.0 [date: 2022-12-15, git hash: 2b156b957]
Copyright (c) 2022 HiGHS under MIT licence terms
INFO:linopy.solvers:Log file at C:\Users\VAUTRIN_A\AppData\Local\Temp\highs.log.
INFO:linopy.model: Optimization successful. Objective value: -3.47e+06
Presolving model
391 rows, 187 cols, 930 nonzeros	
391 rows, 187 cols, 930 nonzeros
Presolve : Reductions: rows 391(-77); columns 187(-1); elements 930(-77)
Solving the presolved LP
Using EKK dual simplex solver - serial
  Iteration        Objective     Infeasibilities num(sum)
          0    -2.1204514665e+07 Pr: 60(41395.5); Du: 0(6.13737e-11) 0s
        210    -3.4742542914e+06 Pr: 0(0) 0s
Solving the original LP from the solution after postsolve
Model   status      : Optimal
Simplex   iterations: 210
Objective value     : -3.4742542914e+06
HiGHS run time      :          0.00
Bus                      London     Norwich  ...      Norway  Norway DC
snapshot                                     ...                       
2015-01-01 00:00:00   35.796244  415.462564  ...  820.035836        0.0
2015-01-01 01:00:00  976.824561  262.606146  ...  854.834047        0.0
2015-01-01 02:00:00  250.587312  418.476353  ...   42.550744        0.0
2015-01-01 03:00:00  130.753145  552.959539  ...  647.548233        0.0
2015-01-01 04:00:00  151.100169  218.159858  ...  884.073873        0.0
2015-01-01 05:00:00  931.857052  791.976266  ...  509.062449        0.0
2015-01-01 06:00:00  289.848287  531.870681  ...  595.607965        0.0
2015-01-01 07:00:00  864.343322   23.513467  ...  291.642450        0.0
2015-01-01 08:00:00  689.577264  970.059068  ...    2.153493        0.0
2015-01-01 09:00:00  627.878986    0.924834  ...  760.740177        0.0

[10 rows x 9 columns]
Load                     London     Norwich  ...      Norway  Manchester
snapshot                                     ...                        
2015-01-01 00:00:00   35.796244  415.462564  ...  820.035836  857.551440
2015-01-01 01:00:00  976.824561  262.606146  ...  854.834047  750.599624
2015-01-01 02:00:00  250.587312  418.476353  ...   42.550744  156.564876
2015-01-01 03:00:00  130.753145  552.959539  ...  647.548233  527.870822
2015-01-01 04:00:00  151.100169  218.159858  ...  884.073873   83.897759
2015-01-01 05:00:00  931.857052  791.976266  ...  509.062449  676.623319
2015-01-01 06:00:00  289.848287  531.870681  ...  595.607965  731.137100
2015-01-01 07:00:00  864.343322   23.513467  ...  291.642450  553.344889
2015-01-01 08:00:00  689.577264  970.059068  ...    2.153493  298.338082
2015-01-01 09:00:00  627.878986    0.924834  ...  760.740177  768.290586

[10 rows x 6 columns]

Process finished with exit code 0
```

**Comment by FabianHofmann** [comment]
Tomorrow we are releasing the a new pypsa version. Probably things will be fixed there. Otherwise you can already install it from the master :)

**Comment by avautrin** [comment]
Hi @FabianHofmann, unfortunately the PyPSA release did not change anything on the dual issue... I've been looking into the linopy code and it seems like the primal values are loaded instead of the dual values from the start (directly in run_highs()). Yet I'm a bit confused that it works for you, could you just please indicate which HiGHS version your are using? 
On my side, highspy 1.5.0.dev0, without any local highs installation.
Thanks a lot!

**Comment by FabianHofmann** [comment]
@avautrin thank you for looking precisely into it! There was indeed a wrong assignment: `highspy` has both the attributes `col_value` and `col_dual`, which I wasn't aware of (`col_value` is just the rhs). I fixed it in #98, would you be so kind to test that things are working correctly?

**Comment by avautrin** [comment]
Thanks a lot @FabianHofmann, now it works perfectly! I guess we can close this thread now, thank you all :)

**Pull request closed without merging**
