### PR TITLE
Add SCIP solver interface

### LINKED ISSUE #29: Any plan to add SCIP as a solver?
[SCIP](https://www.scipopt.org/) and its python library `pyscipopt` also support MILP problems with some configs. So do you have any plan to add it into the solvers list. As an open source solver, I think scip may be better than cbc and glpk in many cases.

```python
import pyscipopt as pso
from pyscipopt import Model
model = Model("prod")
# In order to get dual, needs the following configs
model.setPresolve(pso.SCIP_PARAMSETTING.OFF)
model.setHeuristics(pso.SCIP_PARAMSETTING.OFF)
model.disablePropagation()
# LP algorithm for solving initial LP relaxations (automatic 's'implex, 'p'rimal simplex, 'd'ual simplex, 'b'arrier, barrier with 'c'rossover)
model.setCharParam("lp/initalgorithm","p")
model.setParam('limits/time', 600)


lmp = model.getDualsolLinear(power_balance_cons[bus, ti])
angle = model.getVal(bus_angle[bus, ti])
```

### PR DESCRIPTION
**Pull request by FabianHofmann**
closes #29 

The only thing not suported yet is the passing of the solver options. @loongmxbt  do you habe an idea how to do that with a dictionary?

And the tests require installing SCIP from conda

### CODE REVIEW

**Comment by loongmxbt** [comment]
Hi, I found something in the doc, don't know whether will help. 
https://scipopt.github.io/PySCIPOpt/docs/html/scip_8pyx_source.html#l01351
```python
def setPresolve(self, setting):
         """Set presolving parameter settings.
  
         :param setting: the parameter settings (SCIP_PARAMSETTING)
  
         """
         PY_SCIP_CALL(SCIPsetPresolving(self._scip, setting, True))

def setHeuristics(self, setting):
         """Set heuristics parameter settings.
  
         :param setting: the parameter setting (SCIP_PARAMSETTING)
  
         """
         PY_SCIP_CALL(SCIPsetHeuristics(self._scip, setting, True))
  
def disablePropagation(self, onlyroot=False):
    """Disables propagation in SCIP to avoid modifying the original problem during transformation.

    :param onlyroot: use propagation when root processing is finished (Default value = False)

    """
    self.setIntParam("propagating/maxroundsroot", 0)
    if not onlyroot:
        self.setIntParam("propagating/maxrounds", 0)
```

**Comment by FabianHofmann** [comment]
@loongmxbt thanks that could be a start, important is that we have a functionality that passes a dictionary of options to the the scip model.

**Comment by coroa** [comment]
```python
model.setParams(param_dict)
```
(from https://scipopt.github.io/PySCIPOpt/docs/html/classpyscipopt_1_1scip_1_1Model.html#aa3a8c966371978da6cc3d013d600d0af )

looks like the way to go. The available parameters are documented at https://scipopt.org/doc/html/PARAMETERS.php (that url should also go somewhere into the linopy docs).

The only thing that is somewhat missing are a couple of (let me call them) strategies that can be chosen using specific method calls with constants:
1. `model.setEmphasis` ([python docs](https://scipopt.github.io/PySCIPOpt/docs/html/classpyscipopt_1_1scip_1_1Model.html#ae20e15972fd7cbf119372f340539dfed), [c docs](https://scip.zib.de/doc/html/group__ParameterMethods.php#gab2bc4ccd8d9797f1e1b2d7aaefa6500e)) with 11 options like `pyscipopt.SCIP_PARAMEMPHASIS.{DEFAULT,COUNTER,...}`
2. `model.setHeuristics` ([python docs](https://scipopt.github.io/PySCIPOpt/docs/html/classpyscipopt_1_1scip_1_1Model.html#a64ba79c3b2d2d89ad2b25d7f96ff9734), [c docs](https://scip.zib.de/doc/html/group__ParameterMethods.php#ga4c6399f0b7350398902a5e5dcaa7343c) ) with the options `pyscipopt.SCIP_PARAMSETTING.{DEFAULT,FAST,AGGRESSIVE,OFF}`
3. `model.setPresolve` ([python docs](https://scipopt.github.io/PySCIPOpt/docs/html/classpyscipopt_1_1scip_1_1Model.html#a20e1a2efd3dd0338115068d6a709a0ac), [c docs](https://scip.zib.de/doc/html/group__ParameterMethods.php#gaa40bcb511bcc988f381902d8e719631e)) with the options `pyscipopt.SCIP_PARAMSETTING.{DEFAULT,FAST,AGGRESSIVE,OFF}`

**Comment by coroa** [comment]
I would suggest something like:
```
emphasis = solver_options.pop("setEmphasis")
if emphasis is not None:
    m.setEmphasis(getattr(pyscipopt.SCIP_PARAMEMPHASIS, emphasis.upper()))

heuristics = solver_options.pop("setHeuristics")
if heuristics is not None:
    m.setEmphasis(getattr(pyscipopt.SCIP_PARAMSETTING, heuristics.upper()))

...

m.setParams(solver_options)
```

**Comment by matbesancon** [comment]
hi there, if you need help from the SCIP team to push this forward feel free to ping me :)

**Comment by FabianHofmann** [comment]
Hey @matbesancon, thank you for your offer. We are actually having problems to install pyscipopt on the github CI servers (see https://github.com/PyPSA/linopy/actions/runs/6235226758/job/16924013926?pr=78). Would you have a solution for this?

**Comment by matbesancon** [comment]
hi @FabianHofmann sorry for the delay. Pinging @Opt-Mucca and @mmghannam who have been working on PySCIPOpt.

The easiest way might be to get SCIP & PySCIPOpt through conda if your CI supports it?

**Comment by FabianHofmann** [comment]
@matbesancon thanks for your answer, we can try the `conda` approach, however I would like to avoid it, as it would be mixing the installation interfaces. I am not sure whether you have a trick how to circumvent the error:

```

  × Building wheel for pyscipopt (pyproject.toml) did not run successfully.
  │ exit code: 1
  ╰─> [39 lines of output]
      Assuming that SCIP is installed globally, because SCIPOPTDIR is undefined.
      
      running bdist_wheel
      running build
      running build_py
      creating build
      creating build/lib.linux-x86_64-cpython-39
      creating build/lib.linux-x86_64-cpython-39/pyscipopt
      copying src/pyscipopt/Multidict.py -> build/lib.linux-x86_64-cpython-39/pyscipopt
      ...
      copying src/pyscipopt/sepa.pxi -> build/lib.linux-x86_64-cpython-39/pyscipopt
      running build_ext
      building 'pyscipopt.scip' extension
      creating build/temp.linux-x86_64-cpython-39
      creating build/temp.linux-x86_64-cpython-39/src
      creating build/temp.linux-x86_64-cpython-39/src/pyscipopt
      gcc -Wno-unused-result -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -fPIC -I. -I/opt/hostedtoolcache/Python/3.9.18/x64/include/python3.9 -c src/pyscipopt/scip.c -o build/temp.linux-x86_64-cpython-39/src/pyscipopt/scip.o
      src/pyscipopt/scip.c:775:10: fatal error: scip/scip.h: No such file or directory
        775 | #include "scip/scip.h"
            |          ^~~~~~~~~~~~~
      compilation terminated.
      error: command '/usr/bin/gcc' failed with exit code 1
      [end of output]
```

**Comment by Opt-Mucca** [comment]
@FabianHofmann PySCIPOpt should now be installable via pip with an installation of SCIP (still doesn't work for anything running ARM). Hopefully that helps with your installation interfaces problem

**Comment by FabianHofmann** [comment]
Thanks @matbesancon and @ryanjoneil for the support. There is still a problem with quadratic problems on windows machines. But I will merge it like this, and we can solve the remaining issues later.

**Pull request merged**
